FROM python:3.12-slim

WORKDIR /app

# COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir flask requests python-dotenv

COPY src/ /app/src

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["python", "src/enrichment_service.py"]
